spring:
  jpa:
    show-sql: true
  r2dbc:
    url: r2dbc:pool:h2:mem:///r2dbcdemo?options=DB_CLOSE_DELAY=-1;SCHEMA=DEMO   
    username: sa
    password:    
  flyway:
    url: jdbc:h2:mem:r2dbcdemo;MODE=MSSQLServer
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true  
    schemas: DEMO
    enabled: true
      
  datasource:
    url: jdbc:h2:mem:r2dbcdemo;MODE=MSSQLServer
    username: sa
    password:
    driverClassName: org.h2.Driver   
  h2:
    console:
      enabled: true    
      path: #/h2-console  path has to be defined but value is not effective, i.e. console is in the root 
      port: 8082             